workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v14

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node
    working_directory: ~/working_directory
    steps:
      - run:
          name: Versions
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: Test
          command: npm run coverage
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules

  node-v10:
    <<: *node-base
    docker:
      - image: node:10
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
  node-v14:
    <<: *node-base
    docker:
      - image: node:14
